name: github-webhooks-servant-simple-example
version: 0.0.0
license: MIT
copyright: (c) 2017-2022 Cuedo Control Engineering
author: Kyle Van Berendonck <kyle.vanberendonck@cuedo.com.au>
maintainer: Kyle Van Berendonck <foss@cuedo.com.au>

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates

default-extensions:
  - OverloadedStrings
  - DataKinds
  - TypeFamilies
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - RankNTypes

dependencies:
 - base == 4.*
 - bytestring
 - wai
 - warp
 - github-webhooks
 - servant
 - servant-server
 - servant-github-webhook

executables:
  github-webhooks-servant-example:
    main: Main.hs
    source-dirs: src
