name: github-webhooks
version: 0.10.1

category: GitHub
license: MIT
extra-source-files:
  - package.yaml
  - stack.yaml
  - stack-*.yaml
  - CHANGELOG.md
  - fixtures/*.json
synopsis: Aeson instances for GitHub Webhook payloads.
copyright: (c) 2017-2019 ONROCK
author:
  - Kyle Van Berendonck <kyle.vanberendonck@onrock.online>
  - Christian Sakai <christianmsakai@gmail.com>
  - Thomas DuBuisson <thomas.dubuisson@gmail.com>
  - Rob Berry
  - Domen Kozar <domen@dev.si>
maintainer: Kyle Van Berendonck <foss@onrock.online>
github: onrock-eng/github-webhooks
description:
    Complete instances for decoding GitHub Webhook payloads (using @aeson@).
    See the README at <https://github.com/onrock-eng/github-webhooks#readme> for examples.

ghc-options:
  - -Wall -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -ddump-to-file -ddump-hi

default-extensions:
  - DeriveDataTypeable
  - DeriveGeneric
  - OverloadedStrings

dependencies:
 - base == 4.*
 - aeson
 - bytestring
 - text
 - vector

library:
  source-dirs: src
  dependencies:
    - base16-bytestring
    - cryptonite
    - deepseq
    - deepseq-generics
    - memory
    - time

tests:
  spec:
    source-dirs: spec
    main: Spec.hs
    dependencies:
      - github-webhooks
      - hspec == 2.*
    default-extensions:
      - ScopedTypeVariables
