name: github-webhooks
version: 0.9.1

category: GitHub
license: MIT
extra-source-files:
  - package.yaml
  - stack.yaml
  - CHANGELOG.md
  - fixtures/*.json
synopsis: Aeson instances for GitHub Webhook payloads.
copyright: (c) 2017-2018 OnRock Engineering
author: Kyle Van Berendonck <kyle.vanberendonck@onrock.engineering>
maintainer: Kyle Van Berendonck <foss@onrock.engineering>
github: onrock-eng/github-webhooks
description:
    Complete instances for decoding GitHub Webhook payloads (using @aeson@).
    See the README at <https://github.com/onrock-eng/github-webhooks#readme> for examples.

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

default-extensions:
  - DeriveDataTypeable
  - DeriveGeneric
  - OverloadedStrings

dependencies:
 - base == 4.*
 - aeson
 - bytestring
 - text
 - vector

library:
  source-dirs: src
  dependencies:
    - base16-bytestring
    - cryptonite
    - deepseq
    - deepseq-generics
    - memory
    - time

tests:
  spec:
    source-dirs: spec
    main: Spec.hs
    dependencies:
      - github-webhooks
      - hspec == 2.*
    default-extensions:
      - ScopedTypeVariables
