resolver: lts-11.5
extra-deps:
# Needed for servant examples
- servant-github-webhook-0.3.2.1
packages:
- .
- location: ./examples/servant-simple
  extra-dep: true
- location: ./examples/servant
  extra-dep: true
- location: ./examples/scotty
  extra-dep: true
