name: github-webhooks-scotty-example
version: 0.0.0
license: MIT
copyright: (c) 2017-2022 Cuedo Control Engineering
author: Kyle Van Berendonck <kyle.vanberendonck@cuedo.com.au>
maintainer: Kyle Van Berendonck <foss@cuedo.com.au>
synopsis: Sample program using scotty and github-webhooks together.
description: Sample program using @scotty@ and @github-webhooks@ together.

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates

default-extensions:
  - OverloadedStrings

dependencies:
 - base == 4.*
 - bytestring
 - github-webhooks
 - scotty

executables:
  github-webhooks-scotty-example:
    main: Main.hs
    source-dirs: src
