on: [push]
name: scan-code
jobs:
  scan-hlint:
    name: hlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup hlint'
        uses: rwe/actions-hlint-setup@v1
        with:
          version: '3.1.6'

      - name: 'Run hlint and annotate results'
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["src/", "spec/", "examples/"]'
          fail-on: warning
