on: [push]
name: scan-code
jobs:
  scan-hlint:
    name: hlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - env:
          HLINT_SETUP: "https://raw.github.com/ndmitchell/hlint/master/misc/run.sh"
          HLINT_ARGUMENTS: ". -c -g"
        run: curl -sSL $HLINT_SETUP | sh -s $HLINT_ARGUMENTS
