on: [push]
name: test-windows-latest
jobs:
  test-package:
    name: Test
    runs-on: windows-latest

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml
          - stack-examples.yaml
        stack-version:
          - latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: ${{ matrix.stack-version }}

      - env:
          STACK_YAML: ${{ matrix.stack-yaml }}
        run: |
          stack --skip-ghc-check test --flag github-webhooks:ci --haddock --no-haddock-deps
          stack sdist

      - uses: actions/upload-artifact@v3
        with:
          name: github-webhooks-windows-${{ matrix.stack-yaml }}-${{ github.sha }}
          path: .stack-work/dist/
